### ISSUE TITLE
Documentation WALLET API CALLS is Disappeared

### ISSUE THREAD

**Issue by sergey-chechaev** [BitSharesEurope/docs.bitshares.eu#13]
<img width="1283" alt="2017-08-04 12 42 28" src="https://user-images.githubusercontent.com/4598042/28963675-a78a950a-7912-11e7-9cb9-565869ccd121.png">

**Comment by xeroc** [comment]
sorry about that. it was fixed 5 minutes later ;D

**Comment by sergey-chechaev** [comment]
@xeroc error still actual.
http://docs.bitshares.org/en/master/api/wallet-api.html#wallet-calls

**Comment by xeroc** [comment]
I've set up readthedocs and changed it so that it doesnt have /en/master in the url. I call for a cached version in your browser. Try this one:
http://docs.bitshares.org/api/wallet-api.html#wallet-calls
